import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/providers';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat With Webhook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex min-h-screen"}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
